In [1]:
import numpy as np
np.random.seed(0)
a=np.random.randn(10,3)

In [8]:
a

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877]])

In [3]:
distance_mat = np.linalg.norm(a[:, None, :] - a[None, :, :], axis=-1)

In [9]:
distance_mat

array([[0.        , 2.49131297, 1.46196307, 1.45724587, 1.170334  ,
        2.15505375, 4.01890634, 2.10002982, 2.13668917, 2.3088664 ],
       [2.49131297, 0.        , 2.55072044, 3.49755955, 2.6940159 ,
        2.09120516, 3.68873668, 1.89234565, 3.47600536, 3.46318724],
       [1.46196307, 2.55072044, 0.        , 1.67454275, 0.63998872,
        1.76006208, 2.62697823, 1.23611602, 1.86052257, 2.56957274],
       [1.45724587, 3.49755955, 1.67454275, 0.        , 1.06969011,
        2.14061369, 4.13085387, 2.32429914, 2.82759404, 1.51200463],
       [1.170334  , 2.6940159 , 0.63998872, 1.06969011, 0.        ,
        1.57713705, 3.18338403, 1.40352986, 2.21779582, 1.98544209],
       [2.15505375, 2.09120516, 1.76006208, 2.14061369, 1.57713705,
        0.        , 3.32064189, 0.8872377 , 3.53619747, 1.75408045],
       [4.01890634, 3.68873668, 2.62697823, 4.13085387, 3.18338403,
        3.32064189, 0.        , 2.5196058 , 3.307936  , 4.70390389],
       [2.10002982, 1.89234565, 1.2361160

In [16]:
distance_mat[distance_mat == 0] = np.inf
distance_mat

array([[       inf, 2.49131297, 1.46196307, 1.45724587, 1.170334  ,
        2.15505375, 4.01890634, 2.10002982, 2.13668917, 2.3088664 ],
       [2.49131297,        inf, 2.55072044, 3.49755955, 2.6940159 ,
        2.09120516, 3.68873668, 1.89234565, 3.47600536, 3.46318724],
       [1.46196307, 2.55072044,        inf, 1.67454275, 0.63998872,
        1.76006208, 2.62697823, 1.23611602, 1.86052257, 2.56957274],
       [1.45724587, 3.49755955, 1.67454275,        inf, 1.06969011,
        2.14061369, 4.13085387, 2.32429914, 2.82759404, 1.51200463],
       [1.170334  , 2.6940159 , 0.63998872, 1.06969011,        inf,
        1.57713705, 3.18338403, 1.40352986, 2.21779582, 1.98544209],
       [2.15505375, 2.09120516, 1.76006208, 2.14061369, 1.57713705,
               inf, 3.32064189, 0.8872377 , 3.53619747, 1.75408045],
       [4.01890634, 3.68873668, 2.62697823, 4.13085387, 3.18338403,
        3.32064189,        inf, 2.5196058 , 3.307936  , 4.70390389],
       [2.10002982, 1.89234565, 1.2361160

In [15]:
nn = distance_mat.argmin(axis=0)
print(nn)

[4 7 4 4 2 7 7 5 2 3]
